
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5 #<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_react_dev
  username: rahulk
  password: rahul1234

test:
  <<: *default
  database: rails_react_test
  username: rahulk
  password: rahul1234
#
production:
  <<: *default
  database: rails_react_production
  username: rahulk
  password: rahul1234
